completion:
	for i in githubcl digitaloceancl metacpancl; do \
		appspec completion examples/$$i-appspec.yaml --zsh  > examples/zsh/_$$i; \
		appspec completion examples/$$i-appspec.yaml --bash > examples/bash/$$i.bash; \
	done

appspec:
	for i in githubcl digitaloceancl metacpancl; do \
		./bin/apicli appspec openapi examples/$$i-openapi.yaml --name $$i > examples/$$i-appspec.yaml; \
	done

pod:
	for i in githubcl digitaloceancl metacpancl; do \
		appspec pod examples/$$i-appspec.yaml > examples/pod/$$i.pod; \
	done

html:
	for i in githubcl digitaloceancl metacpancl; do \
		pod2html examples/pod/$$i.pod > examples/html/$$i.html; \
	done

update: appspec completion pod html
